version: '3'

services:
  db:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    depends_on:
      - db
    command: /start.sh
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
