# Generated by Django 2.0.1 on 2018-01-13 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvName',
            fields=[
                ('itemID', models.IntegerField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'invNames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(db_column='regionID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='regionName', max_length=100)),
            ],
            options={
                'db_table': 'mapRegions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('solar_system_id', models.IntegerField(db_column='solarSystemID', primary_key=True, serialize=False)),
                ('solar_system_name', models.CharField(db_column='solarSystemName', max_length=100)),
                ('sun_type_id', models.IntegerField(db_column='sunTypeID')),
                ('security', models.FloatField()),
            ],
            options={
                'db_table': 'mapSolarSystems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Celestial',
            fields=[
                ('item', models.OneToOneField(db_column='itemID', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='sde.InvName')),
                ('type_id', models.IntegerField(db_column='typeID', db_index=True)),
                ('group_id', models.IntegerField(db_column='groupID')),
                ('constellation_id', models.IntegerField(db_column='constellationID', db_index=True)),
                ('region_id', models.IntegerField(db_column='regionID', db_index=True)),
                ('orbit_id', models.IntegerField(db_column='orbitID')),
                ('x', models.FloatField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('itemName', models.CharField(max_length=100)),
                ('security', models.FloatField()),
                ('celestial_index', models.IntegerField(db_column='celestialIndex')),
                ('orbit_index', models.IntegerField(db_column='orbitIndex')),
            ],
            options={
                'db_table': 'mapDenormalize',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StarGate',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('sde.celestial',),
        ),
    ]
