# Generated by Django 2.0.1 on 2018-01-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0004_solarsystemjump'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.IntegerField(db_column='typeID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'invTypes',
                'managed': False,
            },
        ),
    ]
