# Generated by Django 2.0.1 on 2018-01-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
