# Generated by Django 2.0.1 on 2018-01-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180108_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('solarSystemID', models.IntegerField(primary_key=True, serialize=False)),
                ('solarSystemName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mapSolarSystems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Celestial',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='System',
        ),
    ]
