# Generated by Django 2.0.1 on 2018-01-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_celestial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celestial',
            fields=[
                ('itemID', models.IntegerField(primary_key=True, serialize=False)),
                ('typeID', models.IntegerField()),
                ('groupID', models.IntegerField()),
                ('solarSystemID', models.IntegerField()),
                ('constellationID', models.IntegerField()),
                ('regionID', models.IntegerField()),
                ('orbitID', models.IntegerField()),
                ('x', models.FloatField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('itemName', models.CharField(max_length=100)),
                ('security', models.FloatField()),
                ('celestialIndex', models.IntegerField()),
                ('orbitIndex', models.IntegerField()),
            ],
        ),
    ]
