# Generated by Django 2.0.1 on 2018-01-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180109_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celestial',
            options={'managed': False},
        ),
    ]
