# Generated by Django 2.0.1 on 2018-01-16 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sde', '0002_jump'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kill',
            fields=[
                ('kill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(db_index=True)),
                ('ship_type_id', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sde.Celestial')),
                ('solar_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sde.SolarSystem')),
            ],
        ),
    ]
