# Generated by Django 2.0.1 on 2018-01-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kill',
            name='victim_alliance_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kill',
            name='victim_character_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kill',
            name='victim_corporation_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
