# Generated by Django 2.0.1 on 2018-01-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0003_auto_20180128_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kill',
            name='ship_type_id',
        ),
    ]
