# Generated by Django 2.0.1 on 2018-01-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('sso', '0001_initial'), ('sso', '0002_capsuleer_last_login')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capsuleer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('owner_hash', models.CharField(max_length=200)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
