# Generated by Django 2.0.1 on 2018-01-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsuleer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
